import { createFileRoute, Link, notFound } from "@tanstack/react-router";
import { BookOpenText, ChevronRight } from "lucide-react";
import { Backdrop } from "@/components/site/system";
import { getSuite } from "@/data/product-suite";
import { SiteLayout } from "@/components/site/SiteLayout";
import { BrandButton } from "@/components/site/BrandButton";
import { Prose } from "@/components/site/Prose";
import { LEARN_ARTICLES, getLearnArticle, learnProduct, type LearnArticle, type LearnProduct } from "@/data/learn-articles";

/**
 * Explainers with their own card in public/og (generated by screenshots/generate-og.cjs).
 * Any other slug falls back to the generic Learn card rather than pointing at a missing file.
 */
const OG_CARDS = new Set([
  // Cards rendered by screenshots/generate-og.cjs — add a slug here when its card exists.
  "cloud-asset-inventory",
  "finops",
  "cloud-cost-allocation",
  "rto-vs-rpo",
  "cloud-disaster-recovery",
  "agentic-aiops",
  "kspm",
  "code-security",
  "secrets-management",
  "agentless-cloud-security",
  "choke-point",
  "ciem",
  "cloud-attack-path",
  "cloud-risk-quantification",
  "cnapp",
  "cspm",
  "cwpp",
  "dspm",
  "sspm",
]);
const ogImage = (slug: string) => (OG_CARDS.has(slug) ? `/og/learn-${slug}.png` : "/og/learn.png");

/** The closing call to action, matched to the explainer's product. */
const PRODUCT_CTA: Record<LearnProduct, { line: string; to: string; label: string; demo: string }> = {
  platform: {
    line: "Onam Estate discovers every resource across your connected clouds and the relationships between them, through a read-only connection.",
    to: "/estate",
    label: "Explore Onam Estate",
    demo: "estate",
  },
  security: {
    line: "Connect a read-only role for posture scanning. Your first findings arrive with the first scan — across seven clouds and your SaaS platforms.",
    to: "/platform",
    label: "Explore Onam Security",
    demo: "security",
  },
  finops: {
    line: "Onam FinOps works from reconciled billing data: what you spent, who owns it, what you will spend and what you can stop spending.",
    to: "/finops",
    label: "Explore Onam FinOps",
    demo: "finops",
  },
  drm: {
    line: "Onam DRM maps applications and dependencies, reads configured backup and replication, and predicts RTO and RPO against your targets.",
    to: "/disaster-recovery",
    label: "Explore Onam DRM",
    demo: "drm",
  },
  aiops: {
    line: "Onam AIOps is in early access: agents investigate with evidence and propose; a person approves every change.",
    to: "/platform/ai-operations",
    label: "Explore Onam AIOps",
    demo: "aiops",
  },
};
import { seo, SITE_URL, faqJsonLd } from "@/lib/seo";
import { getAuthor, personJsonLd } from "@/data/authors";

/**
 * DefinedTerm + Article. The DefinedTerm carries the short `answer` verbatim,
 * which is what answer engines quote; the Article carries the full body.
 */
function schema(a: LearnArticle) {
  const url = `${SITE_URL}/learn/${a.slug}`;
  const author = getAuthor(a.author);
  return [
    {
      "@context": "https://schema.org",
      "@type": "DefinedTerm",
      name: a.term,
      description: a.answer,
      inDefinedTermSet: {
        "@type": "DefinedTermSet",
        name: "Onam Cloud Platform Glossary",
        url: `${SITE_URL}/learn`,
      },
      url,
    },
    {
      "@context": "https://schema.org",
      "@type": "Article",
      headline: a.question,
      description: a.excerpt,
      mainEntityOfPage: url,
      image: `${SITE_URL}${ogImage(a.slug)}`,
      author: author ? personJsonLd(author) : { "@type": "Organization", name: "Onam" },
      publisher: {
        "@type": "Organization",
        name: "Onam",
        logo: { "@type": "ImageObject", url: `${SITE_URL}/logo-512.png` },
      },
    },
    faqJsonLd(a.faqs),
    {
      "@context": "https://schema.org",
      "@type": "BreadcrumbList",
      itemListElement: [
        { "@type": "ListItem", position: 1, name: "Home", item: `${SITE_URL}/` },
        { "@type": "ListItem", position: 2, name: "Learn", item: `${SITE_URL}/learn` },
        { "@type": "ListItem", position: 3, name: a.term },
      ],
    },
  ];
}

export const Route = createFileRoute("/learn/$slug")({
  loader: ({ params }) => {
    const article = getLearnArticle(params.slug);
    if (!article) throw notFound();
    return { article };
  },
  head: ({ loaderData }) => {
    if (!loaderData) {
      return { meta: [{ title: "Not found — Onam" }, { name: "robots", content: "noindex" }] };
    }
    const a = loaderData.article;
    return seo({
      // No brand suffix: with it, every learn title ran 72–76 characters and was truncated
      // in results at ~60. Google appends the site name from the Organization schema anyway.
      title: a.title,
      description: a.excerpt,
      path: `/learn/${a.slug}`,
      // One card per explainer where screenshots/generate-og.cjs has made one; the generic
      // Learn card otherwise. Adding a card means adding the slug to OG_CARDS too.
      image: ogImage(a.slug),
      ogType: "article",
    });
  },
  component: LearnPage,
  notFoundComponent: NotFound,
});

function NotFound() {
  return (
    <SiteLayout>
      <div className="max-w-3xl mx-auto px-6 py-24 text-center">
        <h1 className="font-display font-black text-3xl text-[#0B1220]">Article not found</h1>
        <p className="mt-3 text-[#475569]">This explainer may have been moved or renamed.</p>
        <div className="mt-6">
          <BrandButton to="/learn">Back to Learn</BrandButton>
        </div>
      </div>
    </SiteLayout>
  );
}

function LearnPage() {
  const { article } = Route.useLoaderData();
  const cta = PRODUCT_CTA[learnProduct(article)];

  // The curated `related` list, split by destination.
  //
  // Until 2026-08-19 this section rendered `LEARN_ARTICLES.slice(0, 3)` — the first three
  // articles in array order, identical on every page — and `article.related` was never
  // read at all. Thirty hand-picked links, including every link from a concept page to
  // its `/platform/` counterpart, existed in the data and reached no reader and no
  // crawler. GSC on 2026-08-19: 39 of 96 pages ranking past position 20, the `/learn/`
  // cluster among them, with `/platform` and `/solutions` never indexed at all.
  //
  // Same reasoning as CLOUD_RELATED_BASE in src/data/solutions-clouds.ts, which fixed the
  // mirror image of this in August and moved Alibaba 29.6 -> 26.3 and IBM 28.9 -> 28.6:
  // pages competing for one intent with no links between them split the signal instead of
  // concentrating it.
  const relatedLearn = article.related
    .filter((r) => r.href.startsWith("/learn/"))
    .map((r) => LEARN_ARTICLES.find((a) => `/learn/${a.slug}` === r.href))
    .filter((a): a is LearnArticle => Boolean(a));
  const relatedDeeper = article.related.filter((r) => !r.href.startsWith("/learn/"));

  // A curated list that has gone stale must not empty the section — falling back keeps
  // the page whole while `ops/catalog.py`-style checks catch the broken href.
  const others = relatedLearn.length
    ? relatedLearn
    : LEARN_ARTICLES.filter((a) => a.slug !== article.slug).slice(0, 3);

  return (
    <SiteLayout>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema(article)) }} />

      <article>
        <section className="relative overflow-hidden border-b border-[#E5E9F0] bg-white">
          {(() => {
            const lp = learnProduct(article);
            const suite = getSuite(lp === "platform" ? "estate" : lp);
            return <Backdrop tone="light" color={suite?.color ?? "#2563EB"} pattern="dots" icon={suite?.icon ?? BookOpenText} />;
          })()}
          <div className="relative max-w-3xl mx-auto px-6 pt-16 pb-12 md:pt-20 md:pb-14">
            <nav className="flex items-center gap-1.5 text-xs text-[#64748B] mb-6">
              <Link to="/learn" className="hover:text-[#2563EB]">Learn</Link>
              <ChevronRight className="w-3.5 h-3.5" />
              <span className="text-[#0B1220]">{article.term}</span>
            </nav>

            <h1 className="font-display font-black text-[#0B1220] text-3xl md:text-[44px] tracking-tight leading-[1.1]">
              {article.question}
            </h1>

            {/* Snippet target: first content on the page, quotable standalone. */}
            <div className="mt-7 rounded-2xl border border-[#DBE7FE] bg-[#F5F8FF] p-6">
              <div className="text-[11px] font-bold uppercase tracking-widest text-[#1D4ED8] mb-2">
                In short
              </div>
              <p className="text-[17px] text-[#0B1220] leading-relaxed font-medium">{article.answer}</p>
            </div>

            <div className="mt-6 flex flex-wrap items-center gap-3 text-sm text-[#64748B]">
              {(() => {
                const author = getAuthor(article.author);
                return author ? (
                  <Link to="/company/team/$slug" params={{ slug: author.slug }} className="font-medium text-[#0B1220] hover:text-[#2563EB]">
                    By {author.name}, {author.role}
                  </Link>
                ) : null;
              })()}
              <span>•</span>
              <span>{article.readTime} read</span>
            </div>
          </div>
        </section>

        <section className="max-w-3xl mx-auto px-6 py-14">
          <Prose source={article.body} />

          <div className="mt-14 pt-10 border-t border-[#E5E9F0]">
            <h2 className="font-display font-extrabold text-2xl text-[#0B1220]">
              Frequently asked questions
            </h2>
            <div className="mt-6 space-y-5">
              {article.faqs.map((f) => (
                <div key={f.q} className="bg-white border border-[#E5E9F0] rounded-2xl p-6">
                  <h3 className="font-display font-bold text-[17px] text-[#0B1220] leading-snug">{f.q}</h3>
                  <p className="mt-2.5 text-[#475569] leading-relaxed">{f.a}</p>
                </div>
              ))}
            </div>
          </div>
        </section>
      </article>

      <section className="bg-[#F7F9FC] border-y border-[#E5E9F0]">
        <div className="max-w-7xl mx-auto px-6 py-14">
          <h2 className="font-display font-extrabold text-2xl text-[#0B1220] mb-6">Keep reading</h2>
          <div className="grid md:grid-cols-3 gap-5">
            {others.map((a) => (
              <Link
                key={a.slug}
                to="/learn/$slug"
                params={{ slug: a.slug }}
                className="group bg-white border border-[#E5E9F0] rounded-2xl p-6 hover:shadow-[0_8px_24px_rgba(16,24,40,.08)] transition"
              >
                <h3 className="font-display font-bold text-[17px] text-[#0B1220] leading-snug group-hover:text-[#2563EB]">
                  {a.question}
                </h3>
                <p className="mt-2 text-sm text-[#475569] line-clamp-3">{a.excerpt}</p>
              </Link>
            ))}
          </div>

          {relatedDeeper.length > 0 && (
            <div className="mt-8 pt-6 border-t border-[#E5E9F0]">
              <h3 className="font-display font-bold text-[15px] text-[#0B1220] mb-3">
                See how Onam does it
              </h3>
              <div className="flex flex-wrap gap-x-6 gap-y-2">
                {relatedDeeper.map((r) => (
                  <a
                    key={r.href}
                    href={r.href}
                    className="text-sm text-[#2563EB] hover:text-[#0B1220] underline underline-offset-4"
                  >
                    {r.label}
                  </a>
                ))}
              </div>
            </div>
          )}
        </div>
      </section>

      <section className="max-w-7xl mx-auto px-6 py-16">
        <div className="bg-white border border-[#E5E9F0] rounded-2xl p-8 md:p-10 flex flex-col md:flex-row items-start md:items-center justify-between gap-6 shadow-[0_1px_3px_rgba(16,24,40,.04)]">
          <div>
            <h2 className="font-display font-extrabold text-2xl text-[#0B1220]">See it on your own cloud</h2>
            <p className="mt-2 text-[#475569] max-w-2xl">{cta.line}</p>
          </div>
          <div className="flex gap-3 shrink-0">
            <BrandButton to="/request-demo" search={{ product: cta.demo }}>Request demo</BrandButton>
            <BrandButton to={cta.to} variant="secondary">{cta.label}</BrandButton>
          </div>
        </div>
      </section>
    </SiteLayout>
  );
}
