/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as RequestDemoRouteImport } from './routes/request-demo'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as CompanyAboutRouteImport } from './routes/company/about'
import { Route as CompanyCareersRouteImport } from './routes/company/careers'
import { Route as CompanyContactRouteImport } from './routes/company/contact'
import { Route as CompanyPrivacyRouteImport } from './routes/company/privacy'
import { Route as CompanySecurityRouteImport } from './routes/company/security'
import { Route as CompanyTermsRouteImport } from './routes/company/terms'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as DocsSplatRouteImport } from './routes/docs.$'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as LearnSlugRouteImport } from './routes/learn.$slug'
import { Route as PlatformIndexRouteImport } from './routes/platform/index'
import { Route as PlatformAgentlessRouteImport } from './routes/platform/agentless'
import { Route as PlatformAiAssistantRouteImport } from './routes/platform/ai-assistant'
import { Route as PlatformAiSecurityRouteImport } from './routes/platform/ai-security'
import { Route as PlatformApiSecurityRouteImport } from './routes/platform/api-security'
import { Route as PlatformAttackPathRouteImport } from './routes/platform/attack-path'
import { Route as PlatformCdrRouteImport } from './routes/platform/cdr'
import { Route as PlatformCiemRouteImport } from './routes/platform/ciem'
import { Route as PlatformCnappRouteImport } from './routes/platform/cnapp'
import { Route as PlatformComplianceRouteImport } from './routes/platform/compliance'
import { Route as PlatformContainerSecurityRouteImport } from './routes/platform/container-security'
import { Route as PlatformCspmRouteImport } from './routes/platform/cspm'
import { Route as PlatformCwppRouteImport } from './routes/platform/cwpp'
import { Route as PlatformDataSecurityRouteImport } from './routes/platform/data-security'
import { Route as PlatformDatabaseSecurityRouteImport } from './routes/platform/database-security'
import { Route as PlatformEncryptionRouteImport } from './routes/platform/encryption'
import { Route as PlatformIamRouteImport } from './routes/platform/iam'
import { Route as PlatformInventoryRouteImport } from './routes/platform/inventory'
import { Route as PlatformNetworkSecurityRouteImport } from './routes/platform/network-security'
import { Route as PlatformRemediationRouteImport } from './routes/platform/remediation'
import { Route as PlatformRiskRouteImport } from './routes/platform/risk'
import { Route as PlatformSaasSecurityRouteImport } from './routes/platform/saas-security'
import { Route as PlatformSecopsRouteImport } from './routes/platform/secops'
import { Route as PlatformTechnologyRouteImport } from './routes/platform/technology'
import { Route as PlatformThreatDetectionRouteImport } from './routes/platform/threat-detection'
import { Route as PlatformVulnerabilityRouteImport } from './routes/platform/vulnerability'
import { Route as ResourcesIndexRouteImport } from './routes/resources/index'
import { Route as ResourcesBlogRouteImport } from './routes/resources/blog'
import { Route as ResourcesScenariosRouteImport } from './routes/resources/scenarios'
import { Route as SolutionsIndexRouteImport } from './routes/solutions/index'
import { Route as SolutionsAlicloudRouteImport } from './routes/solutions/alicloud'
import { Route as SolutionsAwsRouteImport } from './routes/solutions/aws'
import { Route as SolutionsAzureRouteImport } from './routes/solutions/azure'
import { Route as SolutionsFinancialRouteImport } from './routes/solutions/financial'
import { Route as SolutionsGcpRouteImport } from './routes/solutions/gcp'
import { Route as SolutionsGovernmentRouteImport } from './routes/solutions/government'
import { Route as SolutionsHealthcareRouteImport } from './routes/solutions/healthcare'
import { Route as SolutionsIbmRouteImport } from './routes/solutions/ibm'
import { Route as SolutionsKubernetesRouteImport } from './routes/solutions/kubernetes'
import { Route as SolutionsOciRouteImport } from './routes/solutions/oci'
import { Route as ResourcesBlogSlugRouteImport } from './routes/resources/blog.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestDemoRoute = RequestDemoRouteImport.update({
  id: '/request-demo',
  path: '/request-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyAboutRoute = CompanyAboutRouteImport.update({
  id: '/company/about',
  path: '/company/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyCareersRoute = CompanyCareersRouteImport.update({
  id: '/company/careers',
  path: '/company/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyContactRoute = CompanyContactRouteImport.update({
  id: '/company/contact',
  path: '/company/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyPrivacyRoute = CompanyPrivacyRouteImport.update({
  id: '/company/privacy',
  path: '/company/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanySecurityRoute = CompanySecurityRouteImport.update({
  id: '/company/security',
  path: '/company/security',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyTermsRoute = CompanyTermsRouteImport.update({
  id: '/company/terms',
  path: '/company/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => DocsRoute,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnSlugRoute = LearnSlugRouteImport.update({
  id: '/learn/$slug',
  path: '/learn/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformIndexRoute = PlatformIndexRouteImport.update({
  id: '/platform/',
  path: '/platform/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformAgentlessRoute = PlatformAgentlessRouteImport.update({
  id: '/platform/agentless',
  path: '/platform/agentless',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformAiAssistantRoute = PlatformAiAssistantRouteImport.update({
  id: '/platform/ai-assistant',
  path: '/platform/ai-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformAiSecurityRoute = PlatformAiSecurityRouteImport.update({
  id: '/platform/ai-security',
  path: '/platform/ai-security',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformApiSecurityRoute = PlatformApiSecurityRouteImport.update({
  id: '/platform/api-security',
  path: '/platform/api-security',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformAttackPathRoute = PlatformAttackPathRouteImport.update({
  id: '/platform/attack-path',
  path: '/platform/attack-path',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformCdrRoute = PlatformCdrRouteImport.update({
  id: '/platform/cdr',
  path: '/platform/cdr',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformCiemRoute = PlatformCiemRouteImport.update({
  id: '/platform/ciem',
  path: '/platform/ciem',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformCnappRoute = PlatformCnappRouteImport.update({
  id: '/platform/cnapp',
  path: '/platform/cnapp',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformComplianceRoute = PlatformComplianceRouteImport.update({
  id: '/platform/compliance',
  path: '/platform/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformContainerSecurityRoute =
  PlatformContainerSecurityRouteImport.update({
    id: '/platform/container-security',
    path: '/platform/container-security',
    getParentRoute: () => rootRouteImport,
  } as any)
const PlatformCspmRoute = PlatformCspmRouteImport.update({
  id: '/platform/cspm',
  path: '/platform/cspm',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformCwppRoute = PlatformCwppRouteImport.update({
  id: '/platform/cwpp',
  path: '/platform/cwpp',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformDataSecurityRoute = PlatformDataSecurityRouteImport.update({
  id: '/platform/data-security',
  path: '/platform/data-security',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformDatabaseSecurityRoute =
  PlatformDatabaseSecurityRouteImport.update({
    id: '/platform/database-security',
    path: '/platform/database-security',
    getParentRoute: () => rootRouteImport,
  } as any)
const PlatformEncryptionRoute = PlatformEncryptionRouteImport.update({
  id: '/platform/encryption',
  path: '/platform/encryption',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformIamRoute = PlatformIamRouteImport.update({
  id: '/platform/iam',
  path: '/platform/iam',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformInventoryRoute = PlatformInventoryRouteImport.update({
  id: '/platform/inventory',
  path: '/platform/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformNetworkSecurityRoute = PlatformNetworkSecurityRouteImport.update({
  id: '/platform/network-security',
  path: '/platform/network-security',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRemediationRoute = PlatformRemediationRouteImport.update({
  id: '/platform/remediation',
  path: '/platform/remediation',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRiskRoute = PlatformRiskRouteImport.update({
  id: '/platform/risk',
  path: '/platform/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformSaasSecurityRoute = PlatformSaasSecurityRouteImport.update({
  id: '/platform/saas-security',
  path: '/platform/saas-security',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformSecopsRoute = PlatformSecopsRouteImport.update({
  id: '/platform/secops',
  path: '/platform/secops',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformTechnologyRoute = PlatformTechnologyRouteImport.update({
  id: '/platform/technology',
  path: '/platform/technology',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformThreatDetectionRoute = PlatformThreatDetectionRouteImport.update({
  id: '/platform/threat-detection',
  path: '/platform/threat-detection',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformVulnerabilityRoute = PlatformVulnerabilityRouteImport.update({
  id: '/platform/vulnerability',
  path: '/platform/vulnerability',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesBlogRoute = ResourcesBlogRouteImport.update({
  id: '/resources/blog',
  path: '/resources/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesScenariosRoute = ResourcesScenariosRouteImport.update({
  id: '/resources/scenarios',
  path: '/resources/scenarios',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsIndexRoute = SolutionsIndexRouteImport.update({
  id: '/solutions/',
  path: '/solutions/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsAlicloudRoute = SolutionsAlicloudRouteImport.update({
  id: '/solutions/alicloud',
  path: '/solutions/alicloud',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsAwsRoute = SolutionsAwsRouteImport.update({
  id: '/solutions/aws',
  path: '/solutions/aws',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsAzureRoute = SolutionsAzureRouteImport.update({
  id: '/solutions/azure',
  path: '/solutions/azure',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsFinancialRoute = SolutionsFinancialRouteImport.update({
  id: '/solutions/financial',
  path: '/solutions/financial',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsGcpRoute = SolutionsGcpRouteImport.update({
  id: '/solutions/gcp',
  path: '/solutions/gcp',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsGovernmentRoute = SolutionsGovernmentRouteImport.update({
  id: '/solutions/government',
  path: '/solutions/government',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsHealthcareRoute = SolutionsHealthcareRouteImport.update({
  id: '/solutions/healthcare',
  path: '/solutions/healthcare',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsIbmRoute = SolutionsIbmRouteImport.update({
  id: '/solutions/ibm',
  path: '/solutions/ibm',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsKubernetesRoute = SolutionsKubernetesRouteImport.update({
  id: '/solutions/kubernetes',
  path: '/solutions/kubernetes',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsOciRoute = SolutionsOciRouteImport.update({
  id: '/solutions/oci',
  path: '/solutions/oci',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesBlogSlugRoute = ResourcesBlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ResourcesBlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/pricing': typeof PricingRoute
  '/request-demo': typeof RequestDemoRoute
  '/tools': typeof ToolsRoute
  '/company/about': typeof CompanyAboutRoute
  '/company/careers': typeof CompanyCareersRoute
  '/company/contact': typeof CompanyContactRoute
  '/company/privacy': typeof CompanyPrivacyRoute
  '/company/security': typeof CompanySecurityRoute
  '/company/terms': typeof CompanyTermsRoute
  '/docs/$': typeof DocsSplatRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/platform/agentless': typeof PlatformAgentlessRoute
  '/platform/ai-assistant': typeof PlatformAiAssistantRoute
  '/platform/ai-security': typeof PlatformAiSecurityRoute
  '/platform/api-security': typeof PlatformApiSecurityRoute
  '/platform/attack-path': typeof PlatformAttackPathRoute
  '/platform/cdr': typeof PlatformCdrRoute
  '/platform/ciem': typeof PlatformCiemRoute
  '/platform/cnapp': typeof PlatformCnappRoute
  '/platform/compliance': typeof PlatformComplianceRoute
  '/platform/container-security': typeof PlatformContainerSecurityRoute
  '/platform/cspm': typeof PlatformCspmRoute
  '/platform/cwpp': typeof PlatformCwppRoute
  '/platform/data-security': typeof PlatformDataSecurityRoute
  '/platform/database-security': typeof PlatformDatabaseSecurityRoute
  '/platform/encryption': typeof PlatformEncryptionRoute
  '/platform/iam': typeof PlatformIamRoute
  '/platform/inventory': typeof PlatformInventoryRoute
  '/platform/network-security': typeof PlatformNetworkSecurityRoute
  '/platform/remediation': typeof PlatformRemediationRoute
  '/platform/risk': typeof PlatformRiskRoute
  '/platform/saas-security': typeof PlatformSaasSecurityRoute
  '/platform/secops': typeof PlatformSecopsRoute
  '/platform/technology': typeof PlatformTechnologyRoute
  '/platform/threat-detection': typeof PlatformThreatDetectionRoute
  '/platform/vulnerability': typeof PlatformVulnerabilityRoute
  '/resources/blog': typeof ResourcesBlogRouteWithChildren
  '/resources/scenarios': typeof ResourcesScenariosRoute
  '/solutions/alicloud': typeof SolutionsAlicloudRoute
  '/solutions/aws': typeof SolutionsAwsRoute
  '/solutions/azure': typeof SolutionsAzureRoute
  '/solutions/financial': typeof SolutionsFinancialRoute
  '/solutions/gcp': typeof SolutionsGcpRoute
  '/solutions/government': typeof SolutionsGovernmentRoute
  '/solutions/healthcare': typeof SolutionsHealthcareRoute
  '/solutions/ibm': typeof SolutionsIbmRoute
  '/solutions/kubernetes': typeof SolutionsKubernetesRoute
  '/solutions/oci': typeof SolutionsOciRoute
  '/docs/': typeof DocsIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/platform/': typeof PlatformIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/solutions/': typeof SolutionsIndexRoute
  '/resources/blog/$slug': typeof ResourcesBlogSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pricing': typeof PricingRoute
  '/request-demo': typeof RequestDemoRoute
  '/tools': typeof ToolsRoute
  '/company/about': typeof CompanyAboutRoute
  '/company/careers': typeof CompanyCareersRoute
  '/company/contact': typeof CompanyContactRoute
  '/company/privacy': typeof CompanyPrivacyRoute
  '/company/security': typeof CompanySecurityRoute
  '/company/terms': typeof CompanyTermsRoute
  '/docs/$': typeof DocsSplatRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/platform/agentless': typeof PlatformAgentlessRoute
  '/platform/ai-assistant': typeof PlatformAiAssistantRoute
  '/platform/ai-security': typeof PlatformAiSecurityRoute
  '/platform/api-security': typeof PlatformApiSecurityRoute
  '/platform/attack-path': typeof PlatformAttackPathRoute
  '/platform/cdr': typeof PlatformCdrRoute
  '/platform/ciem': typeof PlatformCiemRoute
  '/platform/cnapp': typeof PlatformCnappRoute
  '/platform/compliance': typeof PlatformComplianceRoute
  '/platform/container-security': typeof PlatformContainerSecurityRoute
  '/platform/cspm': typeof PlatformCspmRoute
  '/platform/cwpp': typeof PlatformCwppRoute
  '/platform/data-security': typeof PlatformDataSecurityRoute
  '/platform/database-security': typeof PlatformDatabaseSecurityRoute
  '/platform/encryption': typeof PlatformEncryptionRoute
  '/platform/iam': typeof PlatformIamRoute
  '/platform/inventory': typeof PlatformInventoryRoute
  '/platform/network-security': typeof PlatformNetworkSecurityRoute
  '/platform/remediation': typeof PlatformRemediationRoute
  '/platform/risk': typeof PlatformRiskRoute
  '/platform/saas-security': typeof PlatformSaasSecurityRoute
  '/platform/secops': typeof PlatformSecopsRoute
  '/platform/technology': typeof PlatformTechnologyRoute
  '/platform/threat-detection': typeof PlatformThreatDetectionRoute
  '/platform/vulnerability': typeof PlatformVulnerabilityRoute
  '/resources/blog': typeof ResourcesBlogRouteWithChildren
  '/resources/scenarios': typeof ResourcesScenariosRoute
  '/solutions/alicloud': typeof SolutionsAlicloudRoute
  '/solutions/aws': typeof SolutionsAwsRoute
  '/solutions/azure': typeof SolutionsAzureRoute
  '/solutions/financial': typeof SolutionsFinancialRoute
  '/solutions/gcp': typeof SolutionsGcpRoute
  '/solutions/government': typeof SolutionsGovernmentRoute
  '/solutions/healthcare': typeof SolutionsHealthcareRoute
  '/solutions/ibm': typeof SolutionsIbmRoute
  '/solutions/kubernetes': typeof SolutionsKubernetesRoute
  '/solutions/oci': typeof SolutionsOciRoute
  '/docs': typeof DocsIndexRoute
  '/learn': typeof LearnIndexRoute
  '/platform': typeof PlatformIndexRoute
  '/resources': typeof ResourcesIndexRoute
  '/solutions': typeof SolutionsIndexRoute
  '/resources/blog/$slug': typeof ResourcesBlogSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/pricing': typeof PricingRoute
  '/request-demo': typeof RequestDemoRoute
  '/tools': typeof ToolsRoute
  '/company/about': typeof CompanyAboutRoute
  '/company/careers': typeof CompanyCareersRoute
  '/company/contact': typeof CompanyContactRoute
  '/company/privacy': typeof CompanyPrivacyRoute
  '/company/security': typeof CompanySecurityRoute
  '/company/terms': typeof CompanyTermsRoute
  '/docs/$': typeof DocsSplatRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/platform/agentless': typeof PlatformAgentlessRoute
  '/platform/ai-assistant': typeof PlatformAiAssistantRoute
  '/platform/ai-security': typeof PlatformAiSecurityRoute
  '/platform/api-security': typeof PlatformApiSecurityRoute
  '/platform/attack-path': typeof PlatformAttackPathRoute
  '/platform/cdr': typeof PlatformCdrRoute
  '/platform/ciem': typeof PlatformCiemRoute
  '/platform/cnapp': typeof PlatformCnappRoute
  '/platform/compliance': typeof PlatformComplianceRoute
  '/platform/container-security': typeof PlatformContainerSecurityRoute
  '/platform/cspm': typeof PlatformCspmRoute
  '/platform/cwpp': typeof PlatformCwppRoute
  '/platform/data-security': typeof PlatformDataSecurityRoute
  '/platform/database-security': typeof PlatformDatabaseSecurityRoute
  '/platform/encryption': typeof PlatformEncryptionRoute
  '/platform/iam': typeof PlatformIamRoute
  '/platform/inventory': typeof PlatformInventoryRoute
  '/platform/network-security': typeof PlatformNetworkSecurityRoute
  '/platform/remediation': typeof PlatformRemediationRoute
  '/platform/risk': typeof PlatformRiskRoute
  '/platform/saas-security': typeof PlatformSaasSecurityRoute
  '/platform/secops': typeof PlatformSecopsRoute
  '/platform/technology': typeof PlatformTechnologyRoute
  '/platform/threat-detection': typeof PlatformThreatDetectionRoute
  '/platform/vulnerability': typeof PlatformVulnerabilityRoute
  '/resources/blog': typeof ResourcesBlogRouteWithChildren
  '/resources/scenarios': typeof ResourcesScenariosRoute
  '/solutions/alicloud': typeof SolutionsAlicloudRoute
  '/solutions/aws': typeof SolutionsAwsRoute
  '/solutions/azure': typeof SolutionsAzureRoute
  '/solutions/financial': typeof SolutionsFinancialRoute
  '/solutions/gcp': typeof SolutionsGcpRoute
  '/solutions/government': typeof SolutionsGovernmentRoute
  '/solutions/healthcare': typeof SolutionsHealthcareRoute
  '/solutions/ibm': typeof SolutionsIbmRoute
  '/solutions/kubernetes': typeof SolutionsKubernetesRoute
  '/solutions/oci': typeof SolutionsOciRoute
  '/docs/': typeof DocsIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/platform/': typeof PlatformIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/solutions/': typeof SolutionsIndexRoute
  '/resources/blog/$slug': typeof ResourcesBlogSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/pricing'
    | '/request-demo'
    | '/tools'
    | '/company/about'
    | '/company/careers'
    | '/company/contact'
    | '/company/privacy'
    | '/company/security'
    | '/company/terms'
    | '/docs/$'
    | '/learn/$slug'
    | '/platform/agentless'
    | '/platform/ai-assistant'
    | '/platform/ai-security'
    | '/platform/api-security'
    | '/platform/attack-path'
    | '/platform/cdr'
    | '/platform/ciem'
    | '/platform/cnapp'
    | '/platform/compliance'
    | '/platform/container-security'
    | '/platform/cspm'
    | '/platform/cwpp'
    | '/platform/data-security'
    | '/platform/database-security'
    | '/platform/encryption'
    | '/platform/iam'
    | '/platform/inventory'
    | '/platform/network-security'
    | '/platform/remediation'
    | '/platform/risk'
    | '/platform/saas-security'
    | '/platform/secops'
    | '/platform/technology'
    | '/platform/threat-detection'
    | '/platform/vulnerability'
    | '/resources/blog'
    | '/resources/scenarios'
    | '/solutions/alicloud'
    | '/solutions/aws'
    | '/solutions/azure'
    | '/solutions/financial'
    | '/solutions/gcp'
    | '/solutions/government'
    | '/solutions/healthcare'
    | '/solutions/ibm'
    | '/solutions/kubernetes'
    | '/solutions/oci'
    | '/docs/'
    | '/learn/'
    | '/platform/'
    | '/resources/'
    | '/solutions/'
    | '/resources/blog/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pricing'
    | '/request-demo'
    | '/tools'
    | '/company/about'
    | '/company/careers'
    | '/company/contact'
    | '/company/privacy'
    | '/company/security'
    | '/company/terms'
    | '/docs/$'
    | '/learn/$slug'
    | '/platform/agentless'
    | '/platform/ai-assistant'
    | '/platform/ai-security'
    | '/platform/api-security'
    | '/platform/attack-path'
    | '/platform/cdr'
    | '/platform/ciem'
    | '/platform/cnapp'
    | '/platform/compliance'
    | '/platform/container-security'
    | '/platform/cspm'
    | '/platform/cwpp'
    | '/platform/data-security'
    | '/platform/database-security'
    | '/platform/encryption'
    | '/platform/iam'
    | '/platform/inventory'
    | '/platform/network-security'
    | '/platform/remediation'
    | '/platform/risk'
    | '/platform/saas-security'
    | '/platform/secops'
    | '/platform/technology'
    | '/platform/threat-detection'
    | '/platform/vulnerability'
    | '/resources/blog'
    | '/resources/scenarios'
    | '/solutions/alicloud'
    | '/solutions/aws'
    | '/solutions/azure'
    | '/solutions/financial'
    | '/solutions/gcp'
    | '/solutions/government'
    | '/solutions/healthcare'
    | '/solutions/ibm'
    | '/solutions/kubernetes'
    | '/solutions/oci'
    | '/docs'
    | '/learn'
    | '/platform'
    | '/resources'
    | '/solutions'
    | '/resources/blog/$slug'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/pricing'
    | '/request-demo'
    | '/tools'
    | '/company/about'
    | '/company/careers'
    | '/company/contact'
    | '/company/privacy'
    | '/company/security'
    | '/company/terms'
    | '/docs/$'
    | '/learn/$slug'
    | '/platform/agentless'
    | '/platform/ai-assistant'
    | '/platform/ai-security'
    | '/platform/api-security'
    | '/platform/attack-path'
    | '/platform/cdr'
    | '/platform/ciem'
    | '/platform/cnapp'
    | '/platform/compliance'
    | '/platform/container-security'
    | '/platform/cspm'
    | '/platform/cwpp'
    | '/platform/data-security'
    | '/platform/database-security'
    | '/platform/encryption'
    | '/platform/iam'
    | '/platform/inventory'
    | '/platform/network-security'
    | '/platform/remediation'
    | '/platform/risk'
    | '/platform/saas-security'
    | '/platform/secops'
    | '/platform/technology'
    | '/platform/threat-detection'
    | '/platform/vulnerability'
    | '/resources/blog'
    | '/resources/scenarios'
    | '/solutions/alicloud'
    | '/solutions/aws'
    | '/solutions/azure'
    | '/solutions/financial'
    | '/solutions/gcp'
    | '/solutions/government'
    | '/solutions/healthcare'
    | '/solutions/ibm'
    | '/solutions/kubernetes'
    | '/solutions/oci'
    | '/docs/'
    | '/learn/'
    | '/platform/'
    | '/resources/'
    | '/solutions/'
    | '/resources/blog/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRouteWithChildren
  PricingRoute: typeof PricingRoute
  RequestDemoRoute: typeof RequestDemoRoute
  ToolsRoute: typeof ToolsRoute
  CompanyAboutRoute: typeof CompanyAboutRoute
  CompanyCareersRoute: typeof CompanyCareersRoute
  CompanyContactRoute: typeof CompanyContactRoute
  CompanyPrivacyRoute: typeof CompanyPrivacyRoute
  CompanySecurityRoute: typeof CompanySecurityRoute
  CompanyTermsRoute: typeof CompanyTermsRoute
  LearnSlugRoute: typeof LearnSlugRoute
  PlatformAgentlessRoute: typeof PlatformAgentlessRoute
  PlatformAiAssistantRoute: typeof PlatformAiAssistantRoute
  PlatformAiSecurityRoute: typeof PlatformAiSecurityRoute
  PlatformApiSecurityRoute: typeof PlatformApiSecurityRoute
  PlatformAttackPathRoute: typeof PlatformAttackPathRoute
  PlatformCdrRoute: typeof PlatformCdrRoute
  PlatformCiemRoute: typeof PlatformCiemRoute
  PlatformCnappRoute: typeof PlatformCnappRoute
  PlatformComplianceRoute: typeof PlatformComplianceRoute
  PlatformContainerSecurityRoute: typeof PlatformContainerSecurityRoute
  PlatformCspmRoute: typeof PlatformCspmRoute
  PlatformCwppRoute: typeof PlatformCwppRoute
  PlatformDataSecurityRoute: typeof PlatformDataSecurityRoute
  PlatformDatabaseSecurityRoute: typeof PlatformDatabaseSecurityRoute
  PlatformEncryptionRoute: typeof PlatformEncryptionRoute
  PlatformIamRoute: typeof PlatformIamRoute
  PlatformInventoryRoute: typeof PlatformInventoryRoute
  PlatformNetworkSecurityRoute: typeof PlatformNetworkSecurityRoute
  PlatformRemediationRoute: typeof PlatformRemediationRoute
  PlatformRiskRoute: typeof PlatformRiskRoute
  PlatformSaasSecurityRoute: typeof PlatformSaasSecurityRoute
  PlatformSecopsRoute: typeof PlatformSecopsRoute
  PlatformTechnologyRoute: typeof PlatformTechnologyRoute
  PlatformThreatDetectionRoute: typeof PlatformThreatDetectionRoute
  PlatformVulnerabilityRoute: typeof PlatformVulnerabilityRoute
  ResourcesBlogRoute: typeof ResourcesBlogRouteWithChildren
  ResourcesScenariosRoute: typeof ResourcesScenariosRoute
  SolutionsAlicloudRoute: typeof SolutionsAlicloudRoute
  SolutionsAwsRoute: typeof SolutionsAwsRoute
  SolutionsAzureRoute: typeof SolutionsAzureRoute
  SolutionsFinancialRoute: typeof SolutionsFinancialRoute
  SolutionsGcpRoute: typeof SolutionsGcpRoute
  SolutionsGovernmentRoute: typeof SolutionsGovernmentRoute
  SolutionsHealthcareRoute: typeof SolutionsHealthcareRoute
  SolutionsIbmRoute: typeof SolutionsIbmRoute
  SolutionsKubernetesRoute: typeof SolutionsKubernetesRoute
  SolutionsOciRoute: typeof SolutionsOciRoute
  LearnIndexRoute: typeof LearnIndexRoute
  PlatformIndexRoute: typeof PlatformIndexRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
  SolutionsIndexRoute: typeof SolutionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-demo': {
      id: '/request-demo'
      path: '/request-demo'
      fullPath: '/request-demo'
      preLoaderRoute: typeof RequestDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/about': {
      id: '/company/about'
      path: '/company/about'
      fullPath: '/company/about'
      preLoaderRoute: typeof CompanyAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/careers': {
      id: '/company/careers'
      path: '/company/careers'
      fullPath: '/company/careers'
      preLoaderRoute: typeof CompanyCareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/contact': {
      id: '/company/contact'
      path: '/company/contact'
      fullPath: '/company/contact'
      preLoaderRoute: typeof CompanyContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/privacy': {
      id: '/company/privacy'
      path: '/company/privacy'
      fullPath: '/company/privacy'
      preLoaderRoute: typeof CompanyPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/security': {
      id: '/company/security'
      path: '/company/security'
      fullPath: '/company/security'
      preLoaderRoute: typeof CompanySecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/terms': {
      id: '/company/terms'
      path: '/company/terms'
      fullPath: '/company/terms'
      preLoaderRoute: typeof CompanyTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof DocsRoute
    }
    '/learn/': {
      id: '/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$slug': {
      id: '/learn/$slug'
      path: '/learn/$slug'
      fullPath: '/learn/$slug'
      preLoaderRoute: typeof LearnSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/': {
      id: '/platform/'
      path: '/platform'
      fullPath: '/platform/'
      preLoaderRoute: typeof PlatformIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/agentless': {
      id: '/platform/agentless'
      path: '/platform/agentless'
      fullPath: '/platform/agentless'
      preLoaderRoute: typeof PlatformAgentlessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/ai-assistant': {
      id: '/platform/ai-assistant'
      path: '/platform/ai-assistant'
      fullPath: '/platform/ai-assistant'
      preLoaderRoute: typeof PlatformAiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/ai-security': {
      id: '/platform/ai-security'
      path: '/platform/ai-security'
      fullPath: '/platform/ai-security'
      preLoaderRoute: typeof PlatformAiSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/api-security': {
      id: '/platform/api-security'
      path: '/platform/api-security'
      fullPath: '/platform/api-security'
      preLoaderRoute: typeof PlatformApiSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/attack-path': {
      id: '/platform/attack-path'
      path: '/platform/attack-path'
      fullPath: '/platform/attack-path'
      preLoaderRoute: typeof PlatformAttackPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/cdr': {
      id: '/platform/cdr'
      path: '/platform/cdr'
      fullPath: '/platform/cdr'
      preLoaderRoute: typeof PlatformCdrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/ciem': {
      id: '/platform/ciem'
      path: '/platform/ciem'
      fullPath: '/platform/ciem'
      preLoaderRoute: typeof PlatformCiemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/cnapp': {
      id: '/platform/cnapp'
      path: '/platform/cnapp'
      fullPath: '/platform/cnapp'
      preLoaderRoute: typeof PlatformCnappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/compliance': {
      id: '/platform/compliance'
      path: '/platform/compliance'
      fullPath: '/platform/compliance'
      preLoaderRoute: typeof PlatformComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/container-security': {
      id: '/platform/container-security'
      path: '/platform/container-security'
      fullPath: '/platform/container-security'
      preLoaderRoute: typeof PlatformContainerSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/cspm': {
      id: '/platform/cspm'
      path: '/platform/cspm'
      fullPath: '/platform/cspm'
      preLoaderRoute: typeof PlatformCspmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/cwpp': {
      id: '/platform/cwpp'
      path: '/platform/cwpp'
      fullPath: '/platform/cwpp'
      preLoaderRoute: typeof PlatformCwppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/data-security': {
      id: '/platform/data-security'
      path: '/platform/data-security'
      fullPath: '/platform/data-security'
      preLoaderRoute: typeof PlatformDataSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/database-security': {
      id: '/platform/database-security'
      path: '/platform/database-security'
      fullPath: '/platform/database-security'
      preLoaderRoute: typeof PlatformDatabaseSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/encryption': {
      id: '/platform/encryption'
      path: '/platform/encryption'
      fullPath: '/platform/encryption'
      preLoaderRoute: typeof PlatformEncryptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/iam': {
      id: '/platform/iam'
      path: '/platform/iam'
      fullPath: '/platform/iam'
      preLoaderRoute: typeof PlatformIamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/inventory': {
      id: '/platform/inventory'
      path: '/platform/inventory'
      fullPath: '/platform/inventory'
      preLoaderRoute: typeof PlatformInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/network-security': {
      id: '/platform/network-security'
      path: '/platform/network-security'
      fullPath: '/platform/network-security'
      preLoaderRoute: typeof PlatformNetworkSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/remediation': {
      id: '/platform/remediation'
      path: '/platform/remediation'
      fullPath: '/platform/remediation'
      preLoaderRoute: typeof PlatformRemediationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/risk': {
      id: '/platform/risk'
      path: '/platform/risk'
      fullPath: '/platform/risk'
      preLoaderRoute: typeof PlatformRiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/saas-security': {
      id: '/platform/saas-security'
      path: '/platform/saas-security'
      fullPath: '/platform/saas-security'
      preLoaderRoute: typeof PlatformSaasSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/secops': {
      id: '/platform/secops'
      path: '/platform/secops'
      fullPath: '/platform/secops'
      preLoaderRoute: typeof PlatformSecopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/technology': {
      id: '/platform/technology'
      path: '/platform/technology'
      fullPath: '/platform/technology'
      preLoaderRoute: typeof PlatformTechnologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/threat-detection': {
      id: '/platform/threat-detection'
      path: '/platform/threat-detection'
      fullPath: '/platform/threat-detection'
      preLoaderRoute: typeof PlatformThreatDetectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/vulnerability': {
      id: '/platform/vulnerability'
      path: '/platform/vulnerability'
      fullPath: '/platform/vulnerability'
      preLoaderRoute: typeof PlatformVulnerabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/blog': {
      id: '/resources/blog'
      path: '/resources/blog'
      fullPath: '/resources/blog'
      preLoaderRoute: typeof ResourcesBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/scenarios': {
      id: '/resources/scenarios'
      path: '/resources/scenarios'
      fullPath: '/resources/scenarios'
      preLoaderRoute: typeof ResourcesScenariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/': {
      id: '/solutions/'
      path: '/solutions'
      fullPath: '/solutions/'
      preLoaderRoute: typeof SolutionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/alicloud': {
      id: '/solutions/alicloud'
      path: '/solutions/alicloud'
      fullPath: '/solutions/alicloud'
      preLoaderRoute: typeof SolutionsAlicloudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/aws': {
      id: '/solutions/aws'
      path: '/solutions/aws'
      fullPath: '/solutions/aws'
      preLoaderRoute: typeof SolutionsAwsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/azure': {
      id: '/solutions/azure'
      path: '/solutions/azure'
      fullPath: '/solutions/azure'
      preLoaderRoute: typeof SolutionsAzureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/financial': {
      id: '/solutions/financial'
      path: '/solutions/financial'
      fullPath: '/solutions/financial'
      preLoaderRoute: typeof SolutionsFinancialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/gcp': {
      id: '/solutions/gcp'
      path: '/solutions/gcp'
      fullPath: '/solutions/gcp'
      preLoaderRoute: typeof SolutionsGcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/government': {
      id: '/solutions/government'
      path: '/solutions/government'
      fullPath: '/solutions/government'
      preLoaderRoute: typeof SolutionsGovernmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/healthcare': {
      id: '/solutions/healthcare'
      path: '/solutions/healthcare'
      fullPath: '/solutions/healthcare'
      preLoaderRoute: typeof SolutionsHealthcareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/ibm': {
      id: '/solutions/ibm'
      path: '/solutions/ibm'
      fullPath: '/solutions/ibm'
      preLoaderRoute: typeof SolutionsIbmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/kubernetes': {
      id: '/solutions/kubernetes'
      path: '/solutions/kubernetes'
      fullPath: '/solutions/kubernetes'
      preLoaderRoute: typeof SolutionsKubernetesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/oci': {
      id: '/solutions/oci'
      path: '/solutions/oci'
      fullPath: '/solutions/oci'
      preLoaderRoute: typeof SolutionsOciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/blog/$slug': {
      id: '/resources/blog/$slug'
      path: '/$slug'
      fullPath: '/resources/blog/$slug'
      preLoaderRoute: typeof ResourcesBlogSlugRouteImport
      parentRoute: typeof ResourcesBlogRoute
    }
  }
}

interface DocsRouteChildren {
  DocsSplatRoute: typeof DocsSplatRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsSplatRoute: DocsSplatRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

interface ResourcesBlogRouteChildren {
  ResourcesBlogSlugRoute: typeof ResourcesBlogSlugRoute
}

const ResourcesBlogRouteChildren: ResourcesBlogRouteChildren = {
  ResourcesBlogSlugRoute: ResourcesBlogSlugRoute,
}

const ResourcesBlogRouteWithChildren = ResourcesBlogRoute._addFileChildren(
  ResourcesBlogRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRouteWithChildren,
  PricingRoute: PricingRoute,
  RequestDemoRoute: RequestDemoRoute,
  ToolsRoute: ToolsRoute,
  CompanyAboutRoute: CompanyAboutRoute,
  CompanyCareersRoute: CompanyCareersRoute,
  CompanyContactRoute: CompanyContactRoute,
  CompanyPrivacyRoute: CompanyPrivacyRoute,
  CompanySecurityRoute: CompanySecurityRoute,
  CompanyTermsRoute: CompanyTermsRoute,
  LearnSlugRoute: LearnSlugRoute,
  PlatformAgentlessRoute: PlatformAgentlessRoute,
  PlatformAiAssistantRoute: PlatformAiAssistantRoute,
  PlatformAiSecurityRoute: PlatformAiSecurityRoute,
  PlatformApiSecurityRoute: PlatformApiSecurityRoute,
  PlatformAttackPathRoute: PlatformAttackPathRoute,
  PlatformCdrRoute: PlatformCdrRoute,
  PlatformCiemRoute: PlatformCiemRoute,
  PlatformCnappRoute: PlatformCnappRoute,
  PlatformComplianceRoute: PlatformComplianceRoute,
  PlatformContainerSecurityRoute: PlatformContainerSecurityRoute,
  PlatformCspmRoute: PlatformCspmRoute,
  PlatformCwppRoute: PlatformCwppRoute,
  PlatformDataSecurityRoute: PlatformDataSecurityRoute,
  PlatformDatabaseSecurityRoute: PlatformDatabaseSecurityRoute,
  PlatformEncryptionRoute: PlatformEncryptionRoute,
  PlatformIamRoute: PlatformIamRoute,
  PlatformInventoryRoute: PlatformInventoryRoute,
  PlatformNetworkSecurityRoute: PlatformNetworkSecurityRoute,
  PlatformRemediationRoute: PlatformRemediationRoute,
  PlatformRiskRoute: PlatformRiskRoute,
  PlatformSaasSecurityRoute: PlatformSaasSecurityRoute,
  PlatformSecopsRoute: PlatformSecopsRoute,
  PlatformTechnologyRoute: PlatformTechnologyRoute,
  PlatformThreatDetectionRoute: PlatformThreatDetectionRoute,
  PlatformVulnerabilityRoute: PlatformVulnerabilityRoute,
  ResourcesBlogRoute: ResourcesBlogRouteWithChildren,
  ResourcesScenariosRoute: ResourcesScenariosRoute,
  SolutionsAlicloudRoute: SolutionsAlicloudRoute,
  SolutionsAwsRoute: SolutionsAwsRoute,
  SolutionsAzureRoute: SolutionsAzureRoute,
  SolutionsFinancialRoute: SolutionsFinancialRoute,
  SolutionsGcpRoute: SolutionsGcpRoute,
  SolutionsGovernmentRoute: SolutionsGovernmentRoute,
  SolutionsHealthcareRoute: SolutionsHealthcareRoute,
  SolutionsIbmRoute: SolutionsIbmRoute,
  SolutionsKubernetesRoute: SolutionsKubernetesRoute,
  SolutionsOciRoute: SolutionsOciRoute,
  LearnIndexRoute: LearnIndexRoute,
  PlatformIndexRoute: PlatformIndexRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
  SolutionsIndexRoute: SolutionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
